/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author marcosfa
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Facturas
     */
    public Invoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        txt_fecha = new javax.swing.JTextField();
        txt_ninvoice = new javax.swing.JTextField();
        txtx_nif = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        label_fecha = new javax.swing.JLabel();
        LBL_NFACTURA = new javax.swing.JLabel();
        LBL_NFACTURA1 = new javax.swing.JLabel();
        lbl_datos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea_data = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_cc = new javax.swing.JTextField();
        btn_insert = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_item = new javax.swing.JTextArea();
        txt_und = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        txt_tax = new javax.swing.JTextField();
        txt_fees = new javax.swing.JTextField();
        txt_expenses = new javax.swing.JTextField();
        txt_disbursements = new javax.swing.JTextField();
        txt_fund_provision = new javax.swing.JTextField();
        txt_base_amount = new javax.swing.JTextField();
        txt_iva_2 = new javax.swing.JTextField();
        txt_VAT_amount = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        label_fecha1 = new javax.swing.JLabel();
        label_fecha2 = new javax.swing.JLabel();
        label_fecha3 = new javax.swing.JLabel();
        label_fecha4 = new javax.swing.JLabel();
        label_fecha5 = new javax.swing.JLabel();
        label_fecha6 = new javax.swing.JLabel();
        label_fecha7 = new javax.swing.JLabel();
        label_fecha8 = new javax.swing.JLabel();
        label_fecha9 = new javax.swing.JLabel();
        label_fecha10 = new javax.swing.JLabel();
        label_fecha11 = new javax.swing.JLabel();
        label_fecha12 = new javax.swing.JLabel();
        label_fecha13 = new javax.swing.JLabel();
        label_fecha14 = new javax.swing.JLabel();
        btn_print = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_open = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(157, 188, 227));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Search");

        txt_search.setBackground(new java.awt.Color(204, 204, 204));
        txt_search.setForeground(new java.awt.Color(0, 0, 0));
        txt_search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        txt_fecha.setBackground(new java.awt.Color(204, 204, 204));
        txt_fecha.setForeground(new java.awt.Color(0, 0, 0));
        txt_fecha.setToolTipText("");
        txt_fecha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_ninvoice.setBackground(new java.awt.Color(204, 204, 204));
        txt_ninvoice.setForeground(new java.awt.Color(0, 0, 0));
        txt_ninvoice.setToolTipText("");
        txt_ninvoice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtx_nif.setBackground(new java.awt.Color(204, 204, 204));
        txtx_nif.setForeground(new java.awt.Color(0, 0, 0));
        txtx_nif.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        label_fecha.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha.setText("FECHA");

        LBL_NFACTURA.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        LBL_NFACTURA.setForeground(new java.awt.Color(0, 0, 0));
        LBL_NFACTURA.setText("FACTURA");

        LBL_NFACTURA1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        LBL_NFACTURA1.setForeground(new java.awt.Color(0, 0, 0));
        LBL_NFACTURA1.setText("NIF");

        lbl_datos.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbl_datos.setForeground(new java.awt.Color(0, 0, 0));
        lbl_datos.setText("DATOS");

        txtarea_data.setBackground(new java.awt.Color(204, 204, 204));
        txtarea_data.setColumns(20);
        txtarea_data.setForeground(new java.awt.Color(0, 0, 0));
        txtarea_data.setRows(5);
        txtarea_data.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setViewportView(txtarea_data);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CC", "Concepto", "Und", "Precio", "Importe", "% IVA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        txt_cc.setBackground(new java.awt.Color(204, 204, 204));
        txt_cc.setForeground(new java.awt.Color(0, 0, 0));
        txt_cc.setToolTipText("");
        txt_cc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btn_insert.setBackground(new java.awt.Color(114, 163, 212));
        btn_insert.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_insert.setForeground(new java.awt.Color(0, 0, 0));
        btn_insert.setText("Insert");
        btn_insert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        txt_item.setBackground(new java.awt.Color(204, 204, 204));
        txt_item.setColumns(20);
        txt_item.setForeground(new java.awt.Color(0, 0, 0));
        txt_item.setRows(5);
        txt_item.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane4.setViewportView(txt_item);

        txt_und.setBackground(new java.awt.Color(204, 204, 204));
        txt_und.setForeground(new java.awt.Color(0, 0, 0));
        txt_und.setToolTipText("");
        txt_und.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_price.setBackground(new java.awt.Color(204, 204, 204));
        txt_price.setForeground(new java.awt.Color(0, 0, 0));
        txt_price.setToolTipText("");
        txt_price.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_amount.setBackground(new java.awt.Color(204, 204, 204));
        txt_amount.setForeground(new java.awt.Color(0, 0, 0));
        txt_amount.setToolTipText("");
        txt_amount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_tax.setBackground(new java.awt.Color(204, 204, 204));
        txt_tax.setForeground(new java.awt.Color(0, 0, 0));
        txt_tax.setToolTipText("");
        txt_tax.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_fees.setBackground(new java.awt.Color(204, 204, 204));
        txt_fees.setForeground(new java.awt.Color(0, 0, 0));
        txt_fees.setToolTipText("");
        txt_fees.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_expenses.setBackground(new java.awt.Color(204, 204, 204));
        txt_expenses.setForeground(new java.awt.Color(0, 0, 0));
        txt_expenses.setToolTipText("");
        txt_expenses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_disbursements.setBackground(new java.awt.Color(204, 204, 204));
        txt_disbursements.setForeground(new java.awt.Color(0, 0, 0));
        txt_disbursements.setToolTipText("");
        txt_disbursements.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_fund_provision.setBackground(new java.awt.Color(204, 204, 204));
        txt_fund_provision.setForeground(new java.awt.Color(0, 0, 0));
        txt_fund_provision.setToolTipText("");
        txt_fund_provision.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_base_amount.setBackground(new java.awt.Color(204, 204, 204));
        txt_base_amount.setForeground(new java.awt.Color(0, 0, 0));
        txt_base_amount.setToolTipText("");
        txt_base_amount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_iva_2.setBackground(new java.awt.Color(204, 204, 204));
        txt_iva_2.setForeground(new java.awt.Color(0, 0, 0));
        txt_iva_2.setToolTipText("");
        txt_iva_2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_VAT_amount.setBackground(new java.awt.Color(204, 204, 204));
        txt_VAT_amount.setForeground(new java.awt.Color(0, 0, 0));
        txt_VAT_amount.setToolTipText("");
        txt_VAT_amount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_total.setBackground(new java.awt.Color(204, 204, 204));
        txt_total.setForeground(new java.awt.Color(0, 0, 0));
        txt_total.setToolTipText("");
        txt_total.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        label_fecha1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha1.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha1.setText("Honorarios");

        label_fecha2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha2.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha2.setText("Gastos");

        label_fecha3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha3.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha3.setText("Suplidos");

        label_fecha4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha4.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha4.setText("Prov.Fondos");

        label_fecha5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha5.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha5.setText("Base");

        label_fecha6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha6.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha6.setText("%IVA");

        label_fecha7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha7.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha7.setText("Cuota IVA");

        label_fecha8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha8.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha8.setText("TOTAL:");

        label_fecha9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha9.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha9.setText("CC");

        label_fecha10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha10.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha10.setText("Concepto");

        label_fecha11.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha11.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha11.setText("Und");

        label_fecha12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha12.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha12.setText("Precio");

        label_fecha13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha13.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha13.setText("Importe");

        label_fecha14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        label_fecha14.setForeground(new java.awt.Color(0, 0, 0));
        label_fecha14.setText("%IVA");

        btn_print.setBackground(new java.awt.Color(114, 163, 212));
        btn_print.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_print.setForeground(new java.awt.Color(0, 0, 0));
        btn_print.setText("Print");
        btn_print.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(114, 163, 212));
        btn_save.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_save.setForeground(new java.awt.Color(0, 0, 0));
        btn_save.setText("Save");
        btn_save.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_open.setBackground(new java.awt.Color(114, 163, 212));
        btn_open.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_open.setForeground(new java.awt.Color(0, 0, 0));
        btn_open.setText("Open");
        btn_open.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btn_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel2)
                                .addGap(368, 368, 368))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_cc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(label_fecha9)
                                        .addGap(62, 62, 62)
                                        .addComponent(label_fecha10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label_fecha))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_ninvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LBL_NFACTURA))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LBL_NFACTURA1)
                                            .addComponent(txtx_nif, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_fecha11)
                                    .addComponent(txt_und, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_datos)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(label_fecha12)
                                            .addGap(43, 43, 43)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label_fecha13))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label_fecha14)
                                        .addComponent(txt_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_open, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_fees, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_expenses, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(label_fecha1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(label_fecha2)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_disbursements, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_fecha3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_fecha4)
                                    .addComponent(txt_fund_provision, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(168, 168, 168)
                                .addComponent(label_fecha8)))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_base_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_fecha5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_iva_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_fecha6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_fecha7)
                            .addComponent(txt_VAT_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_fecha)
                            .addComponent(LBL_NFACTURA)
                            .addComponent(LBL_NFACTURA1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ninvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtx_nif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(lbl_datos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_fecha9)
                    .addComponent(label_fecha10)
                    .addComponent(label_fecha11)
                    .addComponent(label_fecha12)
                    .addComponent(label_fecha13)
                    .addComponent(label_fecha14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_und, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_fecha1)
                    .addComponent(label_fecha2)
                    .addComponent(label_fecha3)
                    .addComponent(label_fecha4))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_expenses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_disbursements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fund_provision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_fecha8))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_fecha5)
                            .addComponent(label_fecha6)
                            .addComponent(label_fecha7))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_base_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_iva_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_VAT_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_open, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_insertActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_searchActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_openActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBL_NFACTURA;
    private javax.swing.JLabel LBL_NFACTURA1;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_open;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_fecha;
    private javax.swing.JLabel label_fecha1;
    private javax.swing.JLabel label_fecha10;
    private javax.swing.JLabel label_fecha11;
    private javax.swing.JLabel label_fecha12;
    private javax.swing.JLabel label_fecha13;
    private javax.swing.JLabel label_fecha14;
    private javax.swing.JLabel label_fecha2;
    private javax.swing.JLabel label_fecha3;
    private javax.swing.JLabel label_fecha4;
    private javax.swing.JLabel label_fecha5;
    private javax.swing.JLabel label_fecha6;
    private javax.swing.JLabel label_fecha7;
    private javax.swing.JLabel label_fecha8;
    private javax.swing.JLabel label_fecha9;
    private javax.swing.JLabel lbl_datos;
    private javax.swing.JTextField txt_VAT_amount;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_base_amount;
    private javax.swing.JTextField txt_cc;
    private javax.swing.JTextField txt_disbursements;
    private javax.swing.JTextField txt_expenses;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_fees;
    private javax.swing.JTextField txt_fund_provision;
    private javax.swing.JTextArea txt_item;
    private javax.swing.JTextField txt_iva_2;
    private javax.swing.JTextField txt_ninvoice;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_tax;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_und;
    private javax.swing.JTextArea txtarea_data;
    private javax.swing.JTextField txtx_nif;
    // End of variables declaration//GEN-END:variables
}
